### ISSUE TITLE
Option to use other currency than dollar?

### ISSUE THREAD

**Issue by 1ntroduc3** [jessejputnam/card-collector#16]
Where is this configured in the code? I can try to make some modifications to EUR if possible

**Comment by jessejputnam** [comment]
The API I am pulling from is for a US market price. Unfortunately, that means it's pretty coupled to that price. 

I like this idea too and will add it to my list. If you are looking to do an immediate, temporary fix for yourself in the meantime however, you could go the VIEWS folder, and go to wherever you find the price displayed and wrap it with a conversion.

For example, if you want to show the price in Euros for the card-detail.pug view: 
- under div.info-market-container, find:
     - h2 $#{card.value.market.toFixed(2)}
- Change it to: h2 € #{(card.value.market * 0.94).toFixed(2)}

**Comment by jessejputnam** [comment]
Added a currency preference to the sidebar that converts currencies now. Added Euro, Canada, and Australia. Could do others if wanted. However, since I am connecting to a US market for the prices, I left the add card prices in USD. But the displayed prices of your collection can be converted through the select on the sidebar now.

**Comment by 1ntroduc3** [comment]
Amazing!
